{{- if .Values.migrationJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gophprofile.fullname" . }}-migrator
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.migrationJob.backoffLimit }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gophprofile.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "gophprofile.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./migrator"]
          envFrom:
            - configMapRef:
                name: {{ include "gophprofile.fullname" . }}-config
            - secretRef:
                name: {{ include "gophprofile.fullname" . }}-secrets
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
{{- end }}
