apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gophprofile.fullname" . }}-secrets
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
