apiVersion: v1
kind: Secret
metadata:
  name: avatar-secrets
  labels:
    app: avatar-service
type: Opaque
stringData:
  DATABASE_URL: "postgres://gophprofile:gophprofile@postgres:5432/gophprofile?sslmode=disable"
  MINIO_ACCESS_KEY: "replace-me"
  MINIO_SECRET_KEY: "replace-me"
  rabbitmq-url: "amqp://replace-me"
  s3-access-key: "replace-me"
  s3-secret-key: "replace-me"
